sonar.projectKey=Firefox2100_world-simulation-engine
sonar.organization=firefox2100

sonar.projectName=World Simulation Engine

sonar.sources=src
sonar.tests=tests

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
