sonar.projectKey=Firefox2100_world-simulation-engine
sonar.organization=firefox2100

sonar.projectName=World Simulation Engine

sonar.sources=src,frontend/src
sonar.tests=tests,frontend/src
sonar.test.inclusions=tests/**/*.py,frontend/src/**/*.test.js,frontend/src/**/*.test.jsx
sonar.exclusions=frontend/dist/**,frontend/node_modules/**,frontend/coverage/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
