from .author import author_router
from .background_character import background_character_router
from .character import character_router
from .config import config_router
from .container import container_router
from .equipment import equipment_router
from .event import event_router
from .intent import intent_router
from .item import item_router
from .landmark import landmark_router
from .location import location_router
from .media import media_router
from .memory import memory_router
from .simulation import simulation_router
from .turn import turn_router
from .world import world_router
