from typing import Optional
from fastapi import APIRouter, Query, HTTPException, UploadFile, File, Request, status
from fastapi.responses import StreamingResponse, FileResponse
from pydantic import BaseModel, Field

from world_simulation_engine.misc.enums import TurnType
from world_simulation_engine.model import Simulation, Character, Location, Faction, WorldEntry
from world_simulation_engine.service import FormatNormaliser
from .utils import db_dep, turn_runner_dep, storage_dep


simulation_router = APIRouter(
    prefix="/simulations",
    tags=["Simulation"],
)


class RunSimulationRequest(BaseModel):
    user_input: Optional[str] = Field(
        None,
        description="The user input of this turn."
    )


class RunSimulationResponse(BaseModel):
    run_id: str = Field(
        ...,
        description="The run id of this turn, used to retrieve the result of the turn."
    )


class SimulationListEntry(BaseModel):
    """
    A simplified model for displaying simulations in the front end
    """
    id: int = Field(
        ...,
        description="The unique simulation ID generated by database.",
    )
    name: str = Field(
        ...,
        description="The name of the simulation.",
    )
    description: str = Field(
        ...,
        description="The description of the simulation.",
    )
    language: str = Field(
        ...,
        description="The language of the simulation, as a locale string.",
    )
    enable_tts: bool = Field(
        False,
        description="Whether the simulation should enable text-to-speech.",
    )
    enable_image_generation: bool = Field(
        False,
        description="Whether the simulation should enable image generation.",
    )


class RecordHistory(BaseModel):
    id: int = Field(
        ...,
        description="The ID of the record entry",
    )
    turn_number: int = Field(
        ...,
        description="The turn number of the record entry",
    )
    type: TurnType = Field(
        ...,
        description="The type of this turn",
    )
    narration: str = Field(
        ...,
        description="The narration of this turn",
    )


class FileUploadResponse(BaseModel):
    access_url: str = Field(
        ...,
        description="The URL that can be used to download the file again."
    )


@simulation_router.get("", response_model=list[SimulationListEntry])
async def list_simulations(db: db_dep,
                           limit: int | None = Query(None, ge=1),
                           offset: int = Query(0, ge=0),
                           ) -> list[SimulationListEntry]:
    """
    List all simulations in the database
    \f
    :param db: The database dependency to fetch simulations
    :param limit: The maximum number of simulations to return in a response, for pagination
    :param offset: The amount of simulations to skip in pagination
    :return: A list of simulations
    """
    simulations = await db.simulation.list(limit=limit, offset=offset)

    return [
        SimulationListEntry(
            id=s.id,
            name=s.name,
            description=s.description,
            language=s.language,
            enable_tts=s.enable_tts,
            enable_image_generation=s.enable_image_generation,
        ) for s in simulations
    ]


@simulation_router.get("/runs/{run_id}/events")
async def stream_run_events(run_id: str,
                            turn_runner: turn_runner_dep,
                            ):
    if not turn_runner.has_run(run_id):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Run with id {run_id} not found",
        )

    return StreamingResponse(
        turn_runner.events(run_id),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache, no-store, must-revalidate",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        }
    )


@simulation_router.get("/{simulation_id}", response_model=Simulation)
async def get_simulation(simulation_id: int,
                         db: db_dep,
                         ):
    simulation = await db.simulation.get(simulation_id)

    if not simulation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Simulation with id {simulation_id} not found",
        )

    return simulation


@simulation_router.delete("/{simulation_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_simulation(simulation_id: int,
                            db: db_dep,
                            ):
    await db.simulation.delete(simulation_id)


@simulation_router.post("/{simulation_id}/input", response_model=RunSimulationResponse)
async def run_simulation(simulation_id: int,
                         run_request: RunSimulationRequest,
                         turn_runner: turn_runner_dep
                         ):
    run_id = await turn_runner.start(
        input_data={
            "simulation_id": simulation_id,
            "user_input": run_request.user_input,
        },
        run_name="turn_generator",
        metadata={
            "simulation_id": simulation_id,
        },
        tags=["turn-generator", "simulation"],
    )

    return RunSimulationResponse(
        run_id=run_id,
    )


@simulation_router.get("/{simulation_id}/records", response_model=list[RecordHistory])
async def get_simulation_records(simulation_id: int,
                                 db: db_dep,
                                 limit: int = Query(20, ge=1),
                                 start_from: int | None = Query(None),
                                 ):
    records = await db.record.get_last_records(
        simulation_id=simulation_id,
        last_n=limit,
        start_from=start_from,
    )

    return [
        RecordHistory(
            id=r.id,
            turn_number=r.turn_number,
            type=r.type,
            narration=r.narration,
        ) for r in records
    ]


@simulation_router.get("/{simulation_id}/cover-image", response_class=FileResponse)
async def get_simulation_cover_image(simulation_id: int,
                                     db: db_dep,
                                     storage: storage_dep,
                                     ):
    simulation = await db.simulation.get(simulation_id)
    if not simulation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Simulation with ID {simulation_id} not found",
        )

    image_path = storage.simulation(simulation_id).image.get_path("cover.png")
    if not image_path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Simulation {simulation_id} has no cover image",
        )

    return FileResponse(
        path=image_path,
        media_type="image/png",
        filename=f"simulation-{simulation_id}-cover.png",
    )


@simulation_router.post(
    "/{simulation_id}/cover-image",
    status_code=status.HTTP_201_CREATED,
    response_model=FileUploadResponse,
)
async def upload_simulation_cover_image(simulation_id: int,
                                        request: Request,
                                        db: db_dep,
                                        storage: storage_dep,
                                        file: UploadFile = File(...),
                                        ):
    simulation = await db.simulation.get(simulation_id)
    if not simulation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Simulation with ID {simulation_id} not found",
        )

    normaliser = FormatNormaliser()
    try:
        normalised_bytes = normaliser.normalise_image(await file.read())
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"Error while normalising image: {e}",
        ) from e

    await storage.simulation(simulation_id).image.save(
        file_name="cover.png",
        data=normalised_bytes,
    )

    return FileUploadResponse(
        access_url=str(request.url_for("get_simulation_cover_image", simulation_id=simulation_id)),
    )


@simulation_router.get("/{simulation_id}/characters", response_model=list[Character])
async def list_simulation_characters(simulation_id: int,
                                     db: db_dep,
                                     user_controlled: Optional[bool] = Query(None),
                                     location: Optional[int] = Query(None),
                                     ):
    simulation = await db.simulation.get(simulation_id)
    if not simulation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Simulation with ID {simulation_id} not found",
        )

    characters = await db.character.list(
        simulation_id=simulation_id,
        controlled_by_user=user_controlled,
        location=location,
    )

    return characters


@simulation_router.get("/{simulation_id}/characters/{character_id}", response_model=Character)
async def get_simulation_character(simulation_id: int,
                                   character_id: int,
                                   db: db_dep,
                                   ):
    simulation = await db.simulation.get(simulation_id)
    if not simulation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Simulation with ID {simulation_id} not found",
        )

    character = await db.character.get(character_id)
    if not character:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Character with ID {character_id} not found",
        )

    return character


@simulation_router.get("/{simulation_id}/characters/{character_id}/image", response_class=FileResponse)
async def get_simulation_character_image(simulation_id: int,
                                         character_id: int,
                                         db: db_dep,
                                         storage: storage_dep,
                                         ):
    simulation = await db.simulation.get(simulation_id)
    if not simulation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Simulation with ID {simulation_id} not found",
        )

    character = await db.character.get(character_id)
    if not character:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Character with ID {character_id} not found",
        )

    image_path = storage.simulation(simulation_id).image.get_path(f"character-{character_id}.png")
    if not image_path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Character {character_id} has no image",
        )

    return FileResponse(
        path=image_path,
        media_type="image/png",
        filename=f"simulation-{simulation_id}-cover.png",
    )


@simulation_router.post(
    "/{simulation_id}/characters/{character_id}/image",
    status_code=status.HTTP_201_CREATED,
    response_model=FileUploadResponse,
)
async def upload_simulation_character_image(simulation_id: int,
                                            character_id: int,
                                            request: Request,
                                            db: db_dep,
                                            storage: storage_dep,
                                            file: UploadFile = File(...),
                                            ):
    simulation = await db.simulation.get(simulation_id)
    if not simulation:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Simulation with ID {simulation_id} not found",
        )

    character = await db.character.get(character_id)
    if not character:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Character {character_id} not found",
        )

    normaliser = FormatNormaliser()
    try:
        normalised_bytes = normaliser.normalise_image(await file.read())
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"Error while normalising image: {e}",
        ) from e

    await storage.simulation(simulation_id).image.save(
        file_name=f"character-{character_id}.png",
        data=normalised_bytes,
    )

    return FileUploadResponse(
        access_url=str(request.url_for(
            "get_simulation_character_image",
            simulation_id=simulation_id,
            character_id=character_id
        )),
    )
