from typing import Optional
from pydantic import BaseModel, Field

from world_simulation_engine.misc.enums import LlmProvider


class LlmConnectionCreate(BaseModel):
    provider: LlmProvider = Field(
        ...,
        description="The LLM provider to connect to.",
    )
    name: Optional[str] = Field(
        None,
        description="An optional name for the connection profile.",
    )
    base_url: Optional[str] = Field(
        None,
        description="The base URL for the LLM provider. Can be None if using an official API.",
    )
    api_key: Optional[str] = Field(
        None,
        description="The API key used to access the LLM provider. Can be None if using a self-hosted API.",
    )


class LlmConnectionProfile(LlmConnectionCreate):
    """
    A configuration profile for a LLM provider.
    """
    id: int = Field(
        ...,
        description="The connection profile ID. Generated by the database."
    )


class LlmConnectionProfilePatch(BaseModel):
    name: Optional[str] = Field(
        None,
        description="An optional name for the connection profile.",
    )
    base_url: Optional[str] = Field(
        None,
        description="The base URL for the LLM provider. Can be None if using an official API.",
    )
    api_key: Optional[str] = Field(
        None,
        description="The API key used to access the LLM provider. Can be None if using a self-hosted API.",
    )
