from pydantic import BaseModel, Field

from world_simulation_engine.misc.enums import FactionRelationshipEntity


class FactionRelationship(BaseModel):
    """
    Describe a relationship between a faction and something else.

    For example, to describe "Alice is a member of the book club", set it to:
    - from_type: "character"
    - from_id: The ID of Alice.
    - to_type: "faction"
    - to_id: The ID of the book club.
    - relationship: member
    """
    from_type: FactionRelationshipEntity = Field(
        ...,
        description="The entity type of the relationship origin.",
    )
    from_id: int = Field(
        ...,
        description="The id of the relationship origin.",
    )
    to_type: FactionRelationshipEntity = Field(
        ...,
        description="The entity type of the relationship target.",
    )
    to_id: int = Field(
        ...,
        description="The id of the relationship target.",
    )
    relationship: str = Field(
        ...,
        description="The type of relationship.",
    )


class Faction(BaseModel):
    """
    A faction in the world.
    """
    id: int = Field(
        ...,
        description="The id of this faction. Generated by the database.",
    )
    name: str = Field(
        ...,
        description="The name of the faction.",
    )
    description: str = Field(
        ...,
        description="The description of the faction.",
    )

    attributes: dict[str, list[str]] = Field(
        default_factory=dict,
        description="A dictionary of attributes associated with the faction."
    )
    stats: dict[str, float] = Field(
        default_factory=dict,
        description="A dictionary of stats associated with the faction."
    )
