from typing import Optional
from pydantic import BaseModel, Field

from world_simulation_engine.misc.enums import EquipmentStatus


class Item(BaseModel):
    """
    An item is something that can be owned, but not equipped. Those goes into equipments.
    Additionally, points, credits, currency, or similar entities are also not tracked as items. They should be
    in character stats.
    """
    id: int = Field(
        ...,
        description="The id of the item. Generated by the database.",
    )
    name: str = Field(
        ...,
        description="The name of the item.",
    )
    description: str = Field(
        ...,
        description="The description of the item.",
    )
    quality: Optional[str] = Field(
        None,
        description="Optional quality modifier.",
    )
    quantity: int = Field(
        ...,
        description="The quantity of the item in someone's inventory.",
    )
    unique: bool = Field(
        False,
        description="Whether or not the item is unique. An unique item cannot have more than one quantity.",
    )


class Equipment(BaseModel):
    """
    Equipment is something that can be worn on the character.
    """
    id: int = Field(
        ...,
        description="The id of the item. Generated by the database.",
    )
    name: str = Field(
        ...,
        description="The name of the item.",
    )
    description: str = Field(
        ...,
        description="The description of the item.",
    )
    quality: Optional[str] = Field(
        None,
        description="Optional quality modifier.",
    )
    status: EquipmentStatus = Field(
        ...,
        description="Whether or not the item is equipped.",
    )
