from pydantic import BaseModel, Field


class Entity(BaseModel):
    """
    An entity in a location.
    """
    id: int = Field(
        ...,
        description="The unique identifier of this entity. Generated by database.",
    )
    name: str = Field(
        ...,
        description="The name of the entity.",
    )
    type: str = Field(
        ...,
        description="The type of the entity. Must match what's in the preset.",
    )
    description: str = Field(
        ...,
        description="A description of the entity.",
    )
    status: str = Field(
        ...,
        description="The status of the entity. This will be updated once changed.",
    )
    interactions: list[str] = Field(
        ...,
        description="A list of available interactions one may do with this entity. May be updated when status change.",
    )


class Location(BaseModel):
    """
    A location in the world.
    """
    id: int = Field(
        ...,
        description="The unique identifier of this location. Generated by database.",
    )
    primary_location: str = Field(
        ...,
        description="The primary location of this location. For example, a city, a generic area, etc.",
    )
    detailed_location: str = Field(
        ...,
        description="The detailed location. For example, a place, a house, an address, etc. within the "
                    "primary location.",
    )
    scene: str = Field(
        ...,
        description="The scene inside of the detailed location. For example, living room, a lake in a park, "
                    "etc. that the characters interact with each other within."
    )
    description: str = Field(
        ...,
        description="A description of the location of its view, significance, etc.",
    )

    attributes: dict[str, list[str]] = Field(
        default_factory=dict,
        description="A dictionary of attributes associated with the location."
    )
    stats: dict[str, float] = Field(
        default_factory=dict,
        description="A dictionary of stats associated with the location."
    )

    entities: list[Entity] = Field(
        default_factory=list,
        description="A list of entities in this location.",
    )
