from pydantic import BaseModel, Field

from .data_preset import DataPreset


class Simulation(BaseModel):
    """
    A simulation session, containing the current state and history of a simulation.
    """
    id: int = Field(
        ...,
        description="The unique simulation ID generated by database.",
    )

    name: str = Field(
        ...,
        description="The name of the simulation.",
    )
    description: str = Field(
        ...,
        description="The description of the simulation.",
    )

    data_preset: DataPreset = Field(
        ...,
        description="The data preset for this simulation.",
    )
    language: str = Field(
        ...,
        description="The language of the simulation, as a locale string.",
    )


class SimulationState(BaseModel):
    """
    The current state of a simulation. Stored separately for easier updates.
    """
    id: int = Field(
        ...,
        description="The unique simulation ID. Must match the simulation it represents.",
    )
    scene: int = Field(
        ...,
        description="The scene ID that is currently being described.",
    )

    round_number: int = Field(
        ...,
        description="The current round number of the simulation.",
    )
    state: str = Field(
        ...,
        description="The current state of the simulation, in summarised form."
    )
    time_label: str = Field(
        ...,
        description="The current time in the simulation. Using a string to remain compatible for different "
                    "timing formats.",
    )
