from pydantic import BaseModel, Field

from .data_preset import DataPreset


class Simulation(BaseModel):
    """
    A simulation session, containing the current state and history of a simulation.
    """
    id: int = Field(
        ...,
        description = "The unique simulation ID generated by database.",
    )

    name: str = Field(
        ...,
        description = "The name of the simulation.",
    )
    description: str = Field(
        ...,
        description = "The description of the simulation.",
    )

    data_preset: DataPreset = Field(
        ...,
        description = "The data preset for this simulation.",
    )
