from typing import Optional
from pydantic import BaseModel, Field

from .agent_preset import AgentPreset
from .data_preset import DataPreset
from .embedding_profile import EmbeddingProfile


class Simulation(BaseModel):
    """
    A simulation session, containing the current state and history of a simulation.
    """
    id: int = Field(
        ...,
        description="The unique simulation ID generated by database.",
    )

    name: str = Field(
        ...,
        description="The name of the simulation.",
    )
    description: str = Field(
        ...,
        description="The description of the simulation.",
    )

    agent_preset: AgentPreset = Field(
        ...,
        description="The agent preset for the simulation.",
    )
    data_preset: DataPreset = Field(
        ...,
        description="The data preset for this simulation.",
    )
    embedding_profile: EmbeddingProfile = Field(
        ...,
        description="The embedding profile for this simulation.",
    )
    language: str = Field(
        ...,
        description="The language of the simulation, as a locale string.",
    )


class SimulationState(BaseModel):
    """
    The current state of a simulation. Stored separately for easier updates.
    """
    id: int = Field(
        ...,
        description="The unique simulation ID. Must match the simulation it represents.",
    )
    scene: int = Field(
        ...,
        description="The scene ID that is currently being described.",
    )

    turn_number: int = Field(
        ...,
        description="The current turn number of the simulation.",
    )
    state: str = Field(
        ...,
        description="The current state of the simulation, in summarised form."
    )
    time_label: str = Field(
        ...,
        description="The current time in the simulation. Using a string to remain compatible for different "
                    "timing formats.",
    )
    recent_history_summary: Optional[str] = Field(
        None,
        description="The recent history summary of the simulation.",
    )
    long_term_history_summary: Optional[str] = Field(
        None,
        description="The long term history summary of the simulation.",
    )
