from pydantic import BaseModel, Field

from world_simulation_engine.misc.enums import TaskPriority, TaskStatus, TaskType


class Task(BaseModel):
    """
    A task is something the character needs to complete.

    It could be a formal task like a bounty issued by the guild, or something the character wants to do himself,
    like finding out the truth or bond with someone.
    """
    id: int = Field(
        ...,
        description="The id of the task. Generated by the database.",
    )
    priority: TaskPriority = Field(
        ...,
        description="The priority of the task.",
    )
    status: TaskStatus = Field(
        ...,
        description="The status of the task.",
    )
    type: TaskType = Field(
        ...,
        description="The type of the task.",
    )
    goal: str = Field(
        ...,
        description="The goal of the task.",
    )
    progress: int = Field(
        ...,
        description="The progress of the task, in percentage.",
    )
    source: str = Field(
        ...,
        description="The one who issued the task, or the reason to do it.",
    )
    reward: int = Field(
        ...,
        description="The reward after completing the task.",
    )
