from typing import Optional
from pydantic import BaseModel, Field

from world_simulation_engine.misc.enums import TaskPriority, TaskStatus, TaskType


class Task(BaseModel):
    """
    A task is something the character needs to complete.

    It could be a formal task like a bounty issued by the guild, or something the character wants to do himself,
    like finding out the truth or bond with someone.
    """
    id: int = Field(
        ...,
        description="The id of the task. Generated by the database.",
    )
    character_ids: list[int] = Field(
        ...,
        description="The ids of the characters assigned with the task.",
    )
    private: bool = Field(
        True,
        description="Whether the task is private, only visible to the assigned character themselves.",
    )
    priority: TaskPriority = Field(
        ...,
        description="The priority of the task.",
    )
    status: TaskStatus = Field(
        ...,
        description="The status of the task.",
    )
    type: TaskType = Field(
        ...,
        description="The type of the task.",
    )
    goal: str = Field(
        ...,
        description="The goal of the task.",
    )
    progress: Optional[int] = Field(
        None,
        description="The progress of the task, in percentage. Can be None if the task is a goal, one that "
                    "cannot be measured with progress.",
    )
    source: str = Field(
        ...,
        description="The one who issued the task, or the reason to do it.",
    )
    reward: str = Field(
        ...,
        description="The reward after completing the task.",
    )
