from typing import Optional
from pydantic import BaseModel, Field

from .agent_preset import AgentPreset
from .character import Character
from .data_preset import DataPreset
from .embedding_profile import EmbeddingProfile
from .faction import Faction, FactionRelationship
from .image_generation_preset import ImageGenerationPreset
from .inventory import CharacterInventory
from .location import Location
from .simulation import SimulationState
from .task import Task
from .turn_record import TurnRecord
from .world_entry import WorldEntry


class WorldCreate(BaseModel):
    name: str = Field(
        ...,
        description="The name of the world."
    )
    description: Optional[str] = Field(
        None,
        description="The description of the world."
    )

    agent_preset: Optional[AgentPreset] = Field(
        None,
        description="The agent preset used for this world, containing model configurations and prompt templates."
    )
    image_generation_preset: Optional[ImageGenerationPreset] = Field(
        None,
        description="The image generation preset for this world. Can be None if image generation is not enabled.",
    )
    data_preset: Optional[DataPreset] = Field(
        None,
        description="The data preset used for this world, containing extra data types and their descriptions."
    )
    embedding_profile: Optional[EmbeddingProfile] = Field(
        None,
        description="The embedding profile used for this world, containing configurations for embeddings."
    )
    language: Optional[str] = Field(
        None,
        description="The language of the world, as a locale string."
    )
    act_for_user: bool = Field(
        False,
        description="Whether the simulation should act for the user, or can only control other characters.",
    )
    enable_tts: bool = Field(
        False,
        description="Whether the simulation should enable text-to-speech.",
    )
    enable_image_generation: bool = Field(
        False,
        description="Whether the simulation should enable image generation.",
    )

    state: Optional[SimulationState] = Field(
        None,
        description="The current state of the world."
    )
    characters: Optional[list[Character]] = Field(
        None,
        description="The characters in the world."
    )
    locations: Optional[list[Location]] = Field(
        None,
        description="The locations in the world."
    )
    factions: Optional[list[Faction]] = Field(
        None,
        description="The factions in the world."
    )
    faction_relationships: Optional[list[FactionRelationship]] = Field(
        None,
        description="The relationships between factions in the world."
    )
    inventory: Optional[dict[int, CharacterInventory]] = Field(
        None,
        description="The inventory of characters."
    )
    tasks: Optional[list[Task]] = Field(
        None,
        description="The tasks in the world."
    )
    world_entries: Optional[list[WorldEntry]] = Field(
        None,
        description="The entries in the world."
    )
    turn_records: Optional[list[TurnRecord]] = Field(
        None,
        description="The existing turn records as a starting point."
    )


class World(WorldCreate):
    id: int = Field(
        ...,
        description="The unique ID of this world, generated by the database."
    )
